services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    networks:
      - myapp_net
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # RabbitMQ default port
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
  thetourguy.productsearcherapi:
    container_name: product-search-api
    hostname: tourguy
    depends_on:
      - rabbitmq
    networks:
      - myapp_net
    image: product-search-api
    build:
      context: .
      dockerfile: .\TheTourGuy.ProductSearcherApi\Dockerfile
    ports:
      - "8080:8080"
  thetourguy.SomeOtherGuyWorker:
    container_name: worker-otherguy
    hostname: otherguy
    depends_on:
      rabbitmq:
        condition: service_started
    restart: on-failure
    networks:
      - myapp_net
    image: worker-otherguy
    build:
      context: .
      dockerfile: .\SomeOtherGuyWorker\Dockerfile
  thetourguy.TheBigGuyWorker:
    hostname: bigguy
    container_name: worker-bigguy
    depends_on:
      rabbitmq:
        condition: service_started
    restart: on-failure
    networks:
      - myapp_net
    image: worker-bigguy
    build:
      context: .
      dockerfile: .\TheBigGuyWorker\Dockerfile
  
networks:
  myapp_net:
    name: myapp_net
    
    
